name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Packages
        run: make pkgs

      - name: Create Document PDF
        run: make doc

      - name: Update Release
        uses: johnwbyrd/update-release@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: doc.pdf
