name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Packages
        run: make pkgs

      - name: Create Document PDF
        run: make doc

      - name: Update Document PDF
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/doc.pdf
          asset_name: doc.pdf
          asset_content_type: application/pdf
